# Generated by Django 4.2.4 on 2023-11-01 01:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=6),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 31)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Tasks',
            field=models.ManyToManyField(blank=True, to='walrus.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='walrus.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
