# Generated by Django 4.2.4 on 2023-10-23 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Tasks',
            field=models.ManyToManyField(blank=True, to='walrus.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='walrus.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
