# Generated by Django 4.2.4 on 2023-10-23 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0002_alter_employee_tasks_alter_task_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 23)),
        ),
    ]
