# Generated by Django 4.2.4 on 2023-11-01 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0002_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='ref_project',
        ),
    ]
