# Generated by Django 4.2.4 on 2023-11-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0003_rename_project_task_ref_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='ref_project',
            new_name='project',
        ),
    ]
