# Generated by Django 4.2.5 on 2023-10-23 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0003_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
