# Generated by Django 4.2.4 on 2023-11-01 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0004_rename_ref_project_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='walrus.task_update'),
        ),
    ]
