# Generated by Django 4.2.4 on 2023-10-30 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0004_alter_task_due_date_alter_task_project_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_spent',
            name='in_progress',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='time_spent',
            name='last_clock_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='time_spent',
            name='total_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 30)),
        ),
    ]
