# Generated by Django 4.2.4 on 2023-10-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0005_time_spent_in_progress_time_spent_last_clock_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='time_spent',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
