# Generated by Django 4.2.5 on 2023-10-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0005_remove_task_project_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_complete',
        ),
    ]
