# Generated by Django 4.2.4 on 2023-11-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0005_alter_task_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Date_assigned_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
