# Generated by Django 4.2.4 on 2023-11-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0006_alter_task_date_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
