# Generated by Django 4.2.5 on 2023-10-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0006_remove_task_date_created_remove_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
