# Generated by Django 4.2.4 on 2023-11-01 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0007_alter_employee_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_spent',
            name='total_time',
            field=models.DurationField(blank=True, default=datetime.timedelta),
        ),
    ]
