# Generated by Django 4.2.4 on 2023-10-28 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0008_task_due_date_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_update',
            name='Description',
        ),
        migrations.AddField(
            model_name='task_update',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='walrus.task'),
        ),
        migrations.AddField(
            model_name='task_update',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
