# Generated by Django 4.2.4 on 2023-10-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0009_remove_task_update_description_task_update_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_update',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
