# Generated by Django 4.2.4 on 2023-10-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0011_alter_task_update_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_update',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
